version: '3'

services:
  database:
    image: postgres:14-alpine
    hostname: database
    restart: always
    expose:
      - 5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=stalkee
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stalkee

  bot:
    depends_on:
      - database
    build: .
    hostname: bot
    restart: on-failure
    env_file: .env
    environment:
      - DB_URI=postgres://stalkee:password@database

volumes:
  data:
