version: '3'

services:
  bot:
    build: .
    restart: on-failure
    env_file: .env
    depends_on:
      - postgres
    networks:
      - stalkee
    environment:
      - DB_URI=postgres://postgres:postgres@postgres
    logging:
      driver: json-file
      options:
        max-size: 100M

  postgres:
    image: postgres:16-alpine
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - stalkee
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      driver: json-file
      options:
        max-size: 100M

volumes:
  data:
    driver: local

networks:
  stalkee:
    driver: bridge
